# Generated by Django 4.0.4 on 2022-04-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_remove_user_student_name_remove_user_teacher_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
